# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'application.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from database import database
import datetime

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 9, 301, 135))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.studentIdSubmit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.studentIdSubmit.setObjectName("studentIdSubmit")
        self.verticalLayout.addWidget(self.studentIdSubmit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(340, 10, 431, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.Description = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.Description.setObjectName("Description")
        self.verticalLayout_2.addWidget(self.Description)
        self.submitProduct = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.submitProduct.setObjectName("submitProduct")
        self.verticalLayout_2.addWidget(self.submitProduct)
        #MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.comboBox.addItems([
            'Bag/Backpack',
            'belt',
            'Books',
            'Dress',
            'Hat', 
            'Household',
            'Jacket',
            'Long-sleeve/button up',
            'Pants/Jeans', 
            'Ring/Jewelry',
            'School supplies',
            'Shirts',
            'Shoes',
            'Skirt',
            'Sunglasses',
            'Sweater/Carnigan',
            'Tank Top',
            'Tie',
            'Misc'
        ])

        self.studentIdSubmit.clicked.connect(self.submitId)
        self.submitProduct.clicked.connect(self.subProduct)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def subProduct(self):
        clothesType = self.comboBox.currentText()
        descrption = self.Description.toPlainText()
        db.insertPosts({
            "clothesType":clothesType,
            "descrption": descrption,
            "date": datetime.datetime.utcnow()
        })

    def submitId(self):
        id = self.lineEdit.text()
        db.insertPosts({
            "student":id,
            "date": datetime.datetime.utcnow()
        })

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student Id"))
        self.studentIdSubmit.setText(_translate("MainWindow", "Submit"))
        self.submitProduct.setText(_translate("MainWindow", "Submit"))

if __name__ == "__main__":
    import sys
    db = database( username="Aggie", password="Aggie")
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())